resources:
  smalljob:
    cpu: 2
    mem: 16000
    time: 240
  assemblyjob:
    cpu: 64
    mem: 256000
    time: 2880
  bigjob:
    cpu: 32
    mem: 64000
    time: 480

args:
  input: 
  extn: 
  host_seq: 
  output: 
  sequencing: 
  configfile: 
  temp_dir: 
