resources:
  smalljob:
    threads: 2
    mem_mb: 16000
    runtime: 240
  assemblyjob:
    threads: 64
    mem_mb: 256000
    runtime: 2880
  bigjob:
    threads: 32
    mem_mb: 64000
    runtime: 480

args:
  input: 
  extn: 
  host_seq: 
  output: 
  sequencing: 
  configfile: 
  temp_dir: 

