args:
  configfile: output_tree/config.yaml
  extn: fasta
  host_seq: test-files/am-dh4.fasta
  input: test-files/mitogenomes
  output: output_tree
  sequencing: null
  temp_dir: null
resources:
  assemblyjob:
    cpu: 64
    mem: 256000
    time: 2880
  bigjob:
    cpu: 32
    mem: 64000
    time: 480
  smalljob:
    cpu: 2
    mem: 16000
    time: 240
